#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : donkey_kong.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Mar 07 18:43:03 -0800 2018
# SW Build 2018833 on Wed Oct  4 19:58:22 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: donkey_kong.sh [-help]
# usage: donkey_kong.sh [-lib_map_path]
# usage: donkey_kong.sh [-noclean_files]
# usage: donkey_kong.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'donkey_kong.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm fifo_generator_v13_2_0 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_0 axi_vip_v1_1_0 processing_system7_vip_v1_0_2 lib_pkg_v1_0_2 lib_fifo_v1_0_9 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_16 axi_sg_v4_1_7 axi_dma_v7_1_15 proc_sys_reset_v5_0_12 xlconstant_v1_1_3 xlconcat_v2_1_1 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_16 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_14 axi_data_fifo_v2_1_13 axi_crossbar_v2_1_15 axi_protocol_converter_v2_1_14)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "donkey_kong.sh - Script generated by export_simulation (Vivado v2017.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/fifo_generator_0/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_0 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/fifo_generator_0/sim/fifo_generator_0.v" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0/clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ipshared/3401/src/VGA_controller.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/3401/hdl/AXI_VGA_v1_0.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/sim/donkey_kong_AXI_VGA_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5c1/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/8b42/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_processing_system7_0_0/sim/donkey_kong_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_9 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/462e/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_16 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/0377/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_7 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/8316/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_15 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/9eb7/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_dma_0_0/sim/donkey_kong_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_rst_ps7_0_100M_0/sim/donkey_kong_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_10/sim/bd_1b69_s00a2s_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_16/sim/bd_1b69_s01a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_19/sim/bd_1b69_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/fa70/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_22/sim/bd_1b69_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_20/sim/bd_1b69_m00arn_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_21/sim/bd_1b69_m00rn_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_17/sim/bd_1b69_sarn_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_18/sim/bd_1b69_srn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_13/sim/bd_1b69_s01mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_14/sim/bd_1b69_s01tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_15/sim/bd_1b69_s01sic_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_11/sim/bd_1b69_sarn_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_12/sim/bd_1b69_srn_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_7/sim/bd_1b69_s00mmu_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_8/sim/bd_1b69_s00tr_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_9/sim/bd_1b69_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_2/sim/bd_1b69_arsw_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_3/sim/bd_1b69_rsw_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_4/sim/bd_1b69_awsw_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_5/sim/bd_1b69_wsw_0.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_6/sim/bd_1b69_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_0/sim/bd_1b69_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/sim/bd_1b69_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/sim/bd_1b69.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_33/sim/bd_1b69_s00a2s_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_39/sim/bd_1b69_s01a2s_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_42/sim/bd_1b69_m00s2a_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_45/sim/bd_1b69_m00e_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_43/sim/bd_1b69_m00arn_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_44/sim/bd_1b69_m00rn_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_40/sim/bd_1b69_sarn_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_41/sim/bd_1b69_srn_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_36/sim/bd_1b69_s01mmu_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_37/sim/bd_1b69_s01tr_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_38/sim/bd_1b69_s01sic_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_34/sim/bd_1b69_sarn_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_35/sim/bd_1b69_srn_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_30/sim/bd_1b69_s00mmu_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_31/sim/bd_1b69_s00tr_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_32/sim/bd_1b69_s00sic_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_25/sim/bd_1b69_arsw_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_26/sim/bd_1b69_rsw_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_27/sim/bd_1b69_awsw_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_28/sim/bd_1b69_wsw_1.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_29/sim/bd_1b69_bsw_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_23/sim/bd_1b69_one_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_24/sim/bd_1b69_psr_aclk_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_56/sim/bd_1b69_s00a2s_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_62/sim/bd_1b69_s01a2s_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_65/sim/bd_1b69_m00s2a_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_68/sim/bd_1b69_m00e_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_66/sim/bd_1b69_m00arn_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_67/sim/bd_1b69_m00rn_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_63/sim/bd_1b69_sarn_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_64/sim/bd_1b69_srn_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_59/sim/bd_1b69_s01mmu_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_60/sim/bd_1b69_s01tr_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_61/sim/bd_1b69_s01sic_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_57/sim/bd_1b69_sarn_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_58/sim/bd_1b69_srn_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_53/sim/bd_1b69_s00mmu_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_54/sim/bd_1b69_s00tr_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_55/sim/bd_1b69_s00sic_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_48/sim/bd_1b69_arsw_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_49/sim/bd_1b69_rsw_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_50/sim/bd_1b69_awsw_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_51/sim/bd_1b69_wsw_2.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_52/sim/bd_1b69_bsw_2.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_46/sim/bd_1b69_one_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_47/sim/bd_1b69_psr_aclk_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_79/sim/bd_1b69_s00a2s_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_85/sim/bd_1b69_s01a2s_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_88/sim/bd_1b69_m00s2a_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_91/sim/bd_1b69_m00e_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_89/sim/bd_1b69_m00arn_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_90/sim/bd_1b69_m00rn_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_86/sim/bd_1b69_sarn_7.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_87/sim/bd_1b69_srn_7.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_82/sim/bd_1b69_s01mmu_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_83/sim/bd_1b69_s01tr_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_84/sim/bd_1b69_s01sic_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_80/sim/bd_1b69_sarn_6.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_81/sim/bd_1b69_srn_6.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_76/sim/bd_1b69_s00mmu_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_77/sim/bd_1b69_s00tr_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_78/sim/bd_1b69_s00sic_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_71/sim/bd_1b69_arsw_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_72/sim/bd_1b69_rsw_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_73/sim/bd_1b69_awsw_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_74/sim/bd_1b69_wsw_3.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_75/sim/bd_1b69_bsw_3.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_69/sim/bd_1b69_one_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_70/sim/bd_1b69_psr_aclk_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_102/sim/bd_1b69_s00a2s_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_108/sim/bd_1b69_s01a2s_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_111/sim/bd_1b69_m00s2a_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_114/sim/bd_1b69_m00e_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_112/sim/bd_1b69_m00arn_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_113/sim/bd_1b69_m00rn_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_109/sim/bd_1b69_sarn_9.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_110/sim/bd_1b69_srn_9.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_105/sim/bd_1b69_s01mmu_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_106/sim/bd_1b69_s01tr_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_107/sim/bd_1b69_s01sic_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_103/sim/bd_1b69_sarn_8.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_104/sim/bd_1b69_srn_8.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_99/sim/bd_1b69_s00mmu_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_100/sim/bd_1b69_s00tr_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_101/sim/bd_1b69_s00sic_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_94/sim/bd_1b69_arsw_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_95/sim/bd_1b69_rsw_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_96/sim/bd_1b69_awsw_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_97/sim/bd_1b69_wsw_4.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_98/sim/bd_1b69_bsw_4.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_92/sim/bd_1b69_one_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_93/sim/bd_1b69_psr_aclk_4.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_125/sim/bd_1b69_s00a2s_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_131/sim/bd_1b69_s01a2s_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_134/sim/bd_1b69_m00s2a_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_137/sim/bd_1b69_m00e_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_135/sim/bd_1b69_m00arn_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_136/sim/bd_1b69_m00rn_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_132/sim/bd_1b69_sarn_11.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_133/sim/bd_1b69_srn_11.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_128/sim/bd_1b69_s01mmu_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_129/sim/bd_1b69_s01tr_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_130/sim/bd_1b69_s01sic_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_126/sim/bd_1b69_sarn_10.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_127/sim/bd_1b69_srn_10.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_122/sim/bd_1b69_s00mmu_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_123/sim/bd_1b69_s00tr_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_124/sim/bd_1b69_s00sic_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_117/sim/bd_1b69_arsw_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_118/sim/bd_1b69_rsw_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_119/sim/bd_1b69_awsw_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_120/sim/bd_1b69_wsw_5.sv" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_121/sim/bd_1b69_bsw_5.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_115/sim/bd_1b69_one_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_116/sim/bd_1b69_psr_aclk_5.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_smc_0/sim/donkey_kong_axi_smc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_xlconcat_0_0/sim/donkey_kong_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_16 $vhdlan_opts \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e9c1/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_gpio_0_0/sim/donkey_kong_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_Debouncer_0_0/sim/donkey_kong_Debouncer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/a259/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/74ae/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/a1b8/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_xbar_0/sim/donkey_kong_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/sim/donkey_kong.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_dma_1_0/sim/donkey_kong_axi_dma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_audio_codec_0_0/src/fifo_generator_0_2/sim/fifo_generator_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/ADAU1761_interface.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/adau1761_configuraiton_data.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/adau1761_izedboard.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/audio_top.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/clocking.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/i2c.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/i2s_data_interface.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/src/i3c2.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ipshared/009a/hdl/axi_audio_codec_v1_0.vhd" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_axi_audio_codec_0_0/sim/donkey_kong_axi_audio_codec_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/33cc/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/d5d3/hdl/verilog" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/e0a2/hdl" +incdir+"$ref_dir/../../../../DonkeyKong.srcs/sources_1/bd/donkey_kong/ipshared/571c/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/donkey_kong/ip/donkey_kong_auto_pc_0/sim/donkey_kong_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.donkey_kong xil_defaultlib.glbl -o donkey_kong_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./donkey_kong_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./donkey_kong.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key donkey_kong_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc donkey_kong_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./donkey_kong.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: donkey_kong.sh [-help]\n\
Usage: donkey_kong.sh [-lib_map_path]\n\
Usage: donkey_kong.sh [-reset_run]\n\
Usage: donkey_kong.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
