# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/donkey_kong_axi_smc_0.xci
# IP: The module: 'donkey_kong_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/bd_1b69.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_10/bd_1b69_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_16/bd_1b69_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_19/bd_1b69_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_22/bd_1b69_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_20/bd_1b69_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_21/bd_1b69_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_17/bd_1b69_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_18/bd_1b69_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_13/bd_1b69_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_14/bd_1b69_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_15/bd_1b69_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_11/bd_1b69_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_12/bd_1b69_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_7/bd_1b69_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_8/bd_1b69_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_9/bd_1b69_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_2/bd_1b69_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_3/bd_1b69_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_4/bd_1b69_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_5/bd_1b69_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_6/bd_1b69_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_0/bd_1b69_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'donkey_kong_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_10/bd_1b69_s00a2s_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_16/bd_1b69_s01a2s_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_19/bd_1b69_m00s2a_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_20/bd_1b69_m00arn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_21/bd_1b69_m00rn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_17/bd_1b69_sarn_1_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_18/bd_1b69_srn_1_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_11/bd_1b69_sarn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_12/bd_1b69_srn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_2/bd_1b69_arsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_3/bd_1b69_rsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_4/bd_1b69_awsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_5/bd_1b69_wsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_6/bd_1b69_bsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# IP: C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/donkey_kong_axi_smc_0.xci
# IP: The module: 'donkey_kong_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/bd_1b69.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_10/bd_1b69_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_16/bd_1b69_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_19/bd_1b69_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_22/bd_1b69_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_20/bd_1b69_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_21/bd_1b69_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_17/bd_1b69_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_18/bd_1b69_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_13/bd_1b69_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_14/bd_1b69_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_15/bd_1b69_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_11/bd_1b69_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_12/bd_1b69_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_7/bd_1b69_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_8/bd_1b69_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_9/bd_1b69_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_2/bd_1b69_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_3/bd_1b69_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_4/bd_1b69_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_5/bd_1b69_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_6/bd_1b69_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_0/bd_1b69_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'donkey_kong_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_10/bd_1b69_s00a2s_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_16/bd_1b69_s01a2s_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_19/bd_1b69_m00s2a_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_20/bd_1b69_m00arn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_21/bd_1b69_m00rn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_17/bd_1b69_sarn_1_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_18/bd_1b69_srn_1_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_11/bd_1b69_sarn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_12/bd_1b69_srn_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_2/bd_1b69_arsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_3/bd_1b69_rsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_4/bd_1b69_awsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_5/bd_1b69_wsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_6/bd_1b69_bsw_0_ooc.xdc

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.
