# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_xbar_0/donkey_kong_xbar_0.xci
# IP: The module: 'donkey_kong_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_xbar_0/donkey_kong_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'donkey_kong_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_xbar_0/donkey_kong_xbar_0.xci
# IP: The module: 'donkey_kong_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_xbar_0/donkey_kong_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'donkey_kong_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
