#VGA pins
set_property IOSTANDARD LVCMOS33 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports H_SYNC]
set_property IOSTANDARD LVCMOS33 [get_ports V_SYNC]
set_property PACKAGE_PIN V20 [get_ports {RED[0]}]
set_property PACKAGE_PIN U20 [get_ports {RED[1]}]
set_property PACKAGE_PIN V19 [get_ports {RED[2]}]
set_property PACKAGE_PIN V18 [get_ports {RED[3]}]
set_property PACKAGE_PIN AB22 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN AA22 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN AB21 [get_ports {GREEN[2]}]
set_property PACKAGE_PIN AA21 [get_ports {GREEN[3]}]
set_property PACKAGE_PIN Y21 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN Y20 [get_ports {BLUE[1]}]
set_property PACKAGE_PIN AB20 [get_ports {BLUE[2]}]
set_property PACKAGE_PIN AB19 [get_ports {BLUE[3]}]
set_property PACKAGE_PIN AA19 [get_ports H_SYNC]
set_property PACKAGE_PIN Y19 [get_ports V_SYNC]

#GPIO pins
set_property IOSTANDARD LVCMOS33 [get_ports {Button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Button[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Button[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Button[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Button[6]}]
#set_property PACKAGE_PIN T18 [get_ports {Button[0]}]; #Up
#set_property PACKAGE_PIN R16 [get_ports {Button[1]}]; #Down
#set_property PACKAGE_PIN N15 [get_ports {Button[2]}]; #Left
#set_property PACKAGE_PIN R18 [get_ports {Button[3]}]; #Right
#set_property PACKAGE_PIN P16 [get_ports {Button[4]}]; #Start
#set_property PACKAGE_PIN F22 [get_ports {Button[5]}]; #A
#set_property PACKAGE_PIN G22 [get_ports {Button[6]}]; #B
set_property PACKAGE_PIN Y11 [get_ports {Button[0]}]
set_property PACKAGE_PIN AA11 [get_ports {Button[1]}]
set_property PACKAGE_PIN Y10 [get_ports {Button[2]}]
set_property PACKAGE_PIN AA9 [get_ports {Button[3]}]
set_property PACKAGE_PIN AB11 [get_ports {Button[4]}]
set_property PACKAGE_PIN AB9 [get_ports {Button[5]}]
set_property PACKAGE_PIN AA8 [get_ports {Button[6]}]

set_property PULLDOWN true [get_ports {Button[0]}]
set_property PULLDOWN true [get_ports {Button[1]}]
set_property PULLDOWN true [get_ports {Button[2]}]
set_property PULLDOWN true [get_ports {Button[3]}]
set_property PULLDOWN true [get_ports {Button[4]}]
set_property PULLDOWN true [get_ports {Button[5]}]
set_property PULLDOWN true [get_ports {Button[6]}]

#AUDIO pins
set_property IOSTANDARD LVCMOS33 [get_ports AC_MCLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO0_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO1_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO2_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO3_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SCK_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SDA_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR0_0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR1_0]
set_property PACKAGE_PIN AB2 [get_ports AC_MCLK_0]
set_property PACKAGE_PIN Y8 [get_ports AC_GPIO0_0]
set_property PACKAGE_PIN AA7 [get_ports AC_GPIO1_0]
set_property PACKAGE_PIN AA6 [get_ports AC_GPIO2_0]
set_property PACKAGE_PIN Y6 [get_ports AC_GPIO3_0]
set_property PACKAGE_PIN AB4 [get_ports AC_SCK_0]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA_0]
set_property PACKAGE_PIN AB1 [get_ports AC_ADR0_0]
set_property PACKAGE_PIN Y5 [get_ports AC_ADR1_0]

