# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/slippman/DonkeyKong/.Xil/Vivado-3980-ensc-pit-30/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/slippman/DonkeyKong/DonkeyKong.cache/wt [current_project]
set_property parent.project_path C:/Users/slippman/DonkeyKong/DonkeyKong.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
set_property ip_repo_paths c:/Users/slippman/ip_repo [current_project]
set_property ip_output_repo c:/Users/slippman/DonkeyKong/DonkeyKong.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/hdl/donkey_kong_wrapper.vhd
add_files C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/donkey_kong.bd
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_processing_system7_0_0/donkey_kong_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_dma_0_0/donkey_kong_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_dma_0_0/donkey_kong_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_dma_0_0/donkey_kong_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_rst_ps7_0_100M_0/donkey_kong_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_rst_ps7_0_100M_0/donkey_kong_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_rst_ps7_0_100M_0/donkey_kong_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_10/bd_1b69_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_16/bd_1b69_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_19/bd_1b69_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_20/bd_1b69_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_21/bd_1b69_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_17/bd_1b69_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_18/bd_1b69_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_11/bd_1b69_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_12/bd_1b69_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_2/bd_1b69_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_3/bd_1b69_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_4/bd_1b69_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_5/bd_1b69_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_6/bd_1b69_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/bd_0/ip/ip_1/bd_1b69_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_gpio_0_0/donkey_kong_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_gpio_0_0/donkey_kong_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_gpio_0_0/donkey_kong_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_xbar_0/donkey_kong_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_dma_1_0/donkey_kong_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_dma_1_0/donkey_kong_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_dma_1_0/donkey_kong_axi_dma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_axi_audio_codec_0_0/src/fifo_generator_0_2/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/ip/donkey_kong_auto_pc_0/donkey_kong_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/sources_1/bd/donkey_kong/donkey_kong_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/constrs_1/imports/new/pin_config.xdc
set_property used_in_implementation false [get_files C:/Users/slippman/DonkeyKong/DonkeyKong.srcs/constrs_1/imports/new/pin_config.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top donkey_kong_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef donkey_kong_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file donkey_kong_wrapper_utilization_synth.rpt -pb donkey_kong_wrapper_utilization_synth.pb"
