# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/pin_config.xdc

# Block Designs: bd/donkey_kong/donkey_kong.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong || ORIG_REF_NAME==donkey_kong} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_AXI_VGA_0_0/donkey_kong_AXI_VGA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_AXI_VGA_0_0 || ORIG_REF_NAME==donkey_kong_AXI_VGA_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_processing_system7_0_0/donkey_kong_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_processing_system7_0_0 || ORIG_REF_NAME==donkey_kong_processing_system7_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_axi_dma_0_0/donkey_kong_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_axi_dma_0_0 || ORIG_REF_NAME==donkey_kong_axi_dma_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_ps7_0_axi_periph_0/donkey_kong_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_ps7_0_axi_periph_0 || ORIG_REF_NAME==donkey_kong_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_rst_ps7_0_100M_0/donkey_kong_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_rst_ps7_0_100M_0 || ORIG_REF_NAME==donkey_kong_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_axi_smc_0/donkey_kong_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_axi_smc_0 || ORIG_REF_NAME==donkey_kong_axi_smc_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_xlconcat_0_0/donkey_kong_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_xlconcat_0_0 || ORIG_REF_NAME==donkey_kong_xlconcat_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_axi_gpio_0_0/donkey_kong_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_axi_gpio_0_0 || ORIG_REF_NAME==donkey_kong_axi_gpio_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_Debouncer_0_0/donkey_kong_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_Debouncer_0_0 || ORIG_REF_NAME==donkey_kong_Debouncer_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_xbar_0/donkey_kong_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_xbar_0 || ORIG_REF_NAME==donkey_kong_xbar_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_axi_dma_1_0/donkey_kong_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_axi_dma_1_0 || ORIG_REF_NAME==donkey_kong_axi_dma_1_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_axi_audio_codec_0_0/donkey_kong_axi_audio_codec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_axi_audio_codec_0_0 || ORIG_REF_NAME==donkey_kong_axi_audio_codec_0_0} -quiet] -quiet

# IP: bd/donkey_kong/ip/donkey_kong_auto_pc_0/donkey_kong_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==donkey_kong_auto_pc_0 || ORIG_REF_NAME==donkey_kong_auto_pc_0} -quiet] -quiet

# XDC: bd/donkey_kong/donkey_kong_ooc.xdc
